package gdscript

import com.intellij.codeInsight.editorActions.SimpleTokenSetQuoteHandler
import com.intellij.psi.TokenType.BAD_CHARACTER
import gdscript.psi.ScriptElementTypes.DOUBLE_QUOTED_STRING
import gdscript.psi.ScriptElementTypes.SINGLE_QUOTED_STRING

class ScriptQuoteHandler : SimpleTokenSetQuoteHandler(SINGLE_QUOTED_STRING, DOUBLE_QUOTED_STRING, BAD_CHARACTER)